name: pyspell
channels:
  - conda-forge
  - defaults
dependencies:
  # Core conda‑managed packages
  - python=3.9
  - scikit-learn=1.5.0  
  - numpy
  - cython
  - h5py
  - rawpy
  - seaborn
  - oasis-deconv
  - imbalanced-learn
  - ipykernel
  - pyqt

  # Ensure pip is available
  - pip

  # Install the local toolbox in editable mode via pip
  - pip:
    - suite2p==0.14.2
    - pynwb==2.5.0 
    - pynapple==0.4.0  
    - hdmf<4.0.0,>=3.0.0 
    - xmltodict
    - future
    - peakutils
    - emd-signal
    #- -e .
